apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          volumeMounts:
            - name: docker-socket
              mountPath: /host-docker.sock
              readOnly: true
            - name: host-volume
              mountPath: /host-etc
              readOnly: true
      volumes:
        - name: docker-socket
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        - name: host-volume
          hostPath:
            path: /etc
            type: Directory
