---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
    service: checkout
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080