kind: SBOMSPDXv2p3
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
spec:
  metadata:
    tool:
      name: ''
      version: v0.76.0
    report:
      createdAt: 
  spdx:
    documentDescribes: 
    spdxVersion: SPDX-2.3
    dataLicense: CC0-1.0
    documentNamespace: https://anchore.com/syft/image/quay.io/kubescape/operator@sha256-e38b22d522bf1d622c56efc04e6aac6982a8307ccc0c59951652a63bd6dc38da-81191701-a1b9-44b3-a5fb-d49d64a5383e
    packages: []
    files: 
    annotations: 
    snippets: 
status: {}
metadata:
  name: docker.io-qorbani-golang-hello-world-sha256-a14f3fbf3d5d1c4a000ab2c0c6d5e4633bdb96286a0130fa5b2c5967b934c31f-34c31f
  labels:
    kubescape.io/image-id: docker-io-qorbani-golang-hello-world-sha256-a14f3fbf3d5d1c4a000
    kubescape.io/image-name: docker-io-qorbani-golang-hello-world
  annotations:
    kubescape.io/image-id: docker.io/qorbani/golang-hello-world@sha256:a14f3fbf3d5d1c4a000ab2c0c6d5e4633bdb96286a0130fa5b2c5967b934c31f
    kubescape.io/status: ''
