kind: VulnerabilityManifestSummary
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
spec:
  severities:
    critical:
      all: 0
      relevant: 0
    high:
      all: 1
      relevant: 0
    medium:
      all: 11
      relevant: 0
    low:
      all: 0
      relevant: 0
    negligible:
      all: 11
      relevant: 0
    unknown:
      all: 0
      relevant: 0
status: {}
metadata:
  name: daemonset-fluentbit-gke-fluentbit
  labels:
    kubescape.io/context: non-filtered
    kubescape.io/image-id: gke-gcr-io-fluent-bit-sha256-c03635e4c828b9c6847df9780d6684b45f
    kubescape.io/image-name: gke-gcr-io-fluent-bit
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-container-name: fluentbit
    kubescape.io/workload-kind: daemonset
    kubescape.io/workload-name: fluentbit-gke
    kubescape.io/workload-namespace: kube-system
  annotations:
    kubescape.io/image-id: gke.gcr.io/fluent-bit@sha256:c03635e4c828b9c6847df9780d6684b45ff0a70b1ae8c7e7271283cce472085e
    kubescape.io/status: ''
    kubescape.io/wlid: wlid://cluster-gke_elated-pottery-310110_us-central1-c_cluster-1/namespace-kube-system/daemonset-fluentbit-gke
    kubescape.io/workload-container-name: fluentbit
