apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-sleep
  name: redis-sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sleep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-sleep
    spec:
      containers:
      - args:
        - sleep 1200; redis-server
        command:
        - /bin/sh
        - -c
        image: docker.io/library/redis@sha256:92f3e116c1e719acf78004dd62992c3ad56f68f810c93a8db3fe2351bb9722c2
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: redis-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: redis-data
