apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo
  labels:
    app: acmefit
    service: catalog-db
spec:
  ports:
    - port: 27017
      name: mongo-catalog
      protocol: TCP
  selector:
    app: acmefit
    service: catalog-db

