apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: acmefit
    service: payment
spec:
  ports:
    - name: http-payment
      protocol: TCP
      port: 9000
  selector:
    app: acmefit
    service: payment

