apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: acmefit
    service: users
spec:
  ports:
    - name: http-users
      protocol: TCP
      port: 8083
  selector:
    app: acmefit
    service: users

