apiVersion: v1
kind: Service
metadata:
  name: httpd-proxy
spec:
  selector:
    app: httpd-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
