apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint-deployment-nginx
  labels:
    app: entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      containers:
      - name: entrypoint
        image: danielgrunberger/entrypoint-img@sha256:5af3d3aab902e7968f5c645d241a7a8aa023cab2cd6434c6e5ab359cf03f1113