kind: SeccompProfile
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
metadata:
  name: replicaset-alpine-77b4fdf86c-alpine-optimized
spec:
  containers:
    - name: alpine-optimized
      path: default/replicaset-alpine-77b4fdf86c-alpine-optimized.json
      spec:
        defaultAction: SCMP_ACT_ERRNO
        architectures:
          - SCMP_ARCH_X86_64
          - SCMP_ARCH_X86
          - SCMP_ARCH_X32
        syscalls:
          - names:
            - access
            - arch_prctl
            - brk
            - capget
            - capset
            - chdir
            - clone
            - close
            - connect
            - copy_file_range
            - dup
            - dup2
            - epoll_ctl
            - execve
            - exit_group
            - faccessat2
            - fadvise64
            - fcntl
            - fstat
            - fstatfs
            - futex
            - getcwd
            - getdents64
            - getegid
            - geteuid
            - getgid
            - getpgrp
            - getpid
            - getppid
            - getrandom
            - getuid
            - ioctl
            - lseek
            - mkdir
            - mmap
            - mount
            - mprotect
            - munmap
            - nanosleep
            - newfstatat
            - openat
            - pipe2
            - prctl
            - pread64
            - prlimit64
            - read
            - readlink
            - rseq
            - rt_sigaction
            - rt_sigprocmask
            - rt_sigreturn
            - set_robust_list
            - set_tid_address
            - setgid
            - setgroups
            - setuid
            - socket
            - stat
            - statfs
            - sysinfo
            - uname
            - wait4
            - write
            action: SCMP_ACT_ALLOW
