apiVersion: apps/v1
kind: Deployment
metadata:
  name: http1
  labels:
    app: http1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http1
  template:
    metadata:
      labels:
        app: http1
    spec:
      containers:
        - image: httpd:alpine3.16
          name: http1
          env:
            - name: app
              value: http1