---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-configmap
data:
  example-config.txt: |
    dmVyeSBpbXBvcnRhbnQgZmlsZQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.0.1-php7.4
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: P4ssw0rd0110
            - name: WORDPRESS_DEBUG
              value: "1"
          ports:
            - containerPort: 80
              name: wordpress
          resources:
            requests:
              cpu: 700m
              memory: "1Gi"
            limits:
              cpu: 700m
              memory: "1Gi"
          volumeMounts:
            - name: hostpath-volume
              mountPath: /tmp
      volumes:
        - name: hostpath-volume
          hostPath:
            path: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: operator
spec:
  selector:
    app: operator
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 80
  type: NodePort
---
apiVersion: kubescape.io/v1
kind: ServiceScanResult
metadata:
  name: operator
spec:
  clusterIP: 10.103.207.220
  ports:
    - applicationLayer: ""
      authenticated: false
      port: 4002
      presentationLayer: http
      protocol: TCP
      sessionLayer: tcp
