#!/usr/bin/bash

# Default namespace
NAMESPACE="default"

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --namespace) NAMESPACE="$2"; shift ;;
    esac
    shift
done

kubectl delete ServiceScanResult operator -n "$NAMESPACE"
kubectl wait ServiceScanResult/operator --for=delete --timeout=-1s -n "$NAMESPACE"

kubectl delete deployment operator-deployment -n "$NAMESPACE"
kubectl wait --for=delete deployment/operator-deployment -n "$NAMESPACE" --timeout=90s
