apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2
  labels:
    app: http2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http2
  template:
    metadata:
      labels:
        app: http2
    spec:
      containers:
        - image: httpd:alpine3.16
          name: http2
          env:
            - name: app
              value: http2
