apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alpine
  sessionAffinity: None
  type: ClusterIP
