apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
        worker_rlimit_nofile 8192;
        events {
          worker_connections  4096;
        }
        http {
            server {
                listen      80;
                listen [::]:80;
                location / {
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_pass http://wikijs:3000;
                }
            }
        }