name: Validate System Test JSON Format

on:
  pull_request:
    branches:
      - master
    paths:
      - 'system_test_mapping.json'

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.13'
        cache: 'pip'

    - name: Check JSON format
      run: |
        python3 .github/scripts/json_validator.py